<?php
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 *
 * @package comcal_telegram
 */

/**
 * Telegram options page.
 */
class Telegram_Options extends Comcal_Settings {

    public static function is_configured() {
        $schedule = self::get_option_value( 'schedule' );
        $token    = self::get_option_value( 'bot_token' );
        $channel  = self::get_option_value( 'channel' );
        return 'disabled' !== $schedule && ! empty( $token ) && ! empty( $channel );
    }

    public static function is_weekly_enabled() {
        $schedule = self::get_option_value( 'schedule' );
        return self::is_configured() && 'weekly' === $schedule;
    }

    public static function get_section_title() {
        return 'Telegram';
    }

    public static function get_section_tag() {
        return 'telegram';
    }

    public static function get_option_ids() {
        return array(
            'bot_token' => 'telegram_bot_token_0',
            'channel'   => 'telegram_channel_1',
            'schedule'  => 'schedule_2',
        );
    }

    public static function get_option_labels() {
        return array(
            'bot_token' => 'Telegram Bot Token',
            'channel'   => 'Telegramkanal (@...)',
            'schedule'  => 'Zeitplan',
        );
    }

    public function telegram_bot_token_0_callback() {
        $value = self::get_option_value( 'bot_token' );
        printf(
            '<input class="regular-text" type="text" name="comcal_settings_option_name[telegram_bot_token_0]" id="telegram_bot_token_0" value="%s" placeholder="5556778...">',
            esc_attr( $value )
        );
        ?>
        <p class="description">
            Token des Bot, über welchen die Übersicht versendet wird. Hinweise zur Boterstellung unter <a href="https://core.telegram.org/bots">https://core.telegram.org/bots</a>, Stichwort BotFather.
        </p>
        <?php
    }

    public function telegram_channel_1_callback() {
        $value = self::get_option_value( 'channel' );
        printf(
            '<input class="regular-text" type="text" name="comcal_settings_option_name[telegram_channel_1]" id="telegram_channel_1" value="%s" placeholder="@mein_kanal">',
            esc_attr( $value )
        );
        ?>
        <p class="description">
            Telegramkanal, in welchem der Bot die Übersicht erstellen soll. Der Bot muss in diesem Kanal als Admin hinzugefügt worden sein.
        </p>
        <?php
    }

    public function schedule_2_callback() {
        $value = self::get_option_value( 'schedule' );
        ?>
        <select name="comcal_settings_option_name[schedule_2]" id="schedule_2">
            <?php $selected = 'disabled' === $value ? 'selected' : ''; ?>
            <option value="disabled" <?php echo $selected; ?>>Deaktiviert</option>
            <?php $selected = ( $value && 'weekly' === $value ) ? 'selected' : ''; ?>
            <option value="weekly" <?php echo $selected; ?>>Wöchentliche Übersicht</option>
        </select>
        <p class="description">
            Wenn aktiviert, dann wird ab Sonntag eine Veranstaltungsübersicht der kommenden Woche (Montag bis Sonntag) in den Telegrammkanal gepostet.
            Etwa alle 15 Minuten wird überprüft, ob es Änderungen oder neue Veranstaltungen gibt. In diesem Fall wird der vorhandene Post aktualisiert.
        </p>
        <?php
    }

}

if ( is_admin() ) {
    Comcal_Settings::add_settings_instance( new Telegram_Options() );
}
