name: PHP Unit Tests

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run Unit Tests
      uses: php-actions/phpunit@v3
      with:
        php_version: "7.4"
